//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjTravelDateT1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Companion()
        {
            this.CompanionList = new HashSet<CompanionList>();
        }
    
        public int CompanionID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string IDNumber { get; set; }
        public string Phone { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
    
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanionList> CompanionList { get; set; }
    }
}
