//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjTravelDateT1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TraveldateEntities : DbContext
    {
        public TraveldateEntities()
            : base("name=TraveldateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CityList> CityList { get; set; }
        public virtual DbSet<CommentList> CommentList { get; set; }
        public virtual DbSet<CommentPhotoList> CommentPhotoList { get; set; }
        public virtual DbSet<Companion> Companion { get; set; }
        public virtual DbSet<CompanionList> CompanionList { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<CountryList> CountryList { get; set; }
        public virtual DbSet<Coupon> Coupon { get; set; }
        public virtual DbSet<CouponList> CouponList { get; set; }
        public virtual DbSet<Favorite> Favorite { get; set; }
        public virtual DbSet<LevelList> LevelList { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrderStatusList> OrderStatusList { get; set; }
        public virtual DbSet<PaymentList> PaymentList { get; set; }
        public virtual DbSet<ProductCategory> ProductCategory { get; set; }
        public virtual DbSet<ProductList> ProductList { get; set; }
        public virtual DbSet<ProductPhotoList> ProductPhotoList { get; set; }
        public virtual DbSet<ProductTagDetails> ProductTagDetails { get; set; }
        public virtual DbSet<ProductTagList> ProductTagList { get; set; }
        public virtual DbSet<ProductTypeList> ProductTypeList { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Trip> Trip { get; set; }
        public virtual DbSet<TripDetail> TripDetail { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
    }
}
