//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjTravelDateT1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductList()
        {
            this.CommentList = new HashSet<CommentList>();
            this.Favorite = new HashSet<Favorite>();
            this.ProductPhotoList = new HashSet<ProductPhotoList>();
            this.ProductTagList = new HashSet<ProductTagList>();
            this.Trip = new HashSet<Trip>();
        }
    
        public int ProductID { get; set; }
        public int CompanyID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public Nullable<bool> ExamineStatus { get; set; }
        public string PlanName { get; set; }
        public string PlanDescription { get; set; }
        public Nullable<bool> Discontinued { get; set; }
        public string Outline { get; set; }
        public string OutlineForSearch { get; set; }
        public string Place { get; set; }
    
        public virtual CityList CityList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentList> CommentList { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite> Favorite { get; set; }
        public virtual ProductTypeList ProductTypeList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPhotoList> ProductPhotoList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductTagList> ProductTagList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trip> Trip { get; set; }
    }
}
