//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjTravelDateT1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trip()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
            this.TripDetail = new HashSet<TripDetail>();
        }
    
        public int TripID { get; set; }
        public int ProductID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> MinNum { get; set; }
        public Nullable<int> MaxNum { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<System.DateTime> DiscountExpirationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual ProductList ProductList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TripDetail> TripDetail { get; set; }
    }
}
